### PR TITLE
Solve issues with python 3.10

### PR DESCRIPTION
**Pull request by jose-lopes**
I am using Arch Linux which uses the python version 3.10 and blink started to crash on startup.
I created this patch and applied it into blink and it is working again, now using python 3.10.

The package for archlinux is https://aur.archlinux.org/packages/blink/ already with this patch.

### CODE REVIEW

**Comment by tijmenNL** [comment]
Thanks for the pull request. Can you explain why you cast those values to int?

**Comment by jose-lopes** [comment]
Python 3.10 doesn't handle implicit float to int conversion like previous versions.
Blink crashed on startup and it had a lot of errors similar to the next.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/blink/widgets/buttons.py", line 406, in drawComplexControl
    self.drawToolButtonComplexControl(option, painter, widget)
  File "/usr/lib/python3.10/site-packages/blink/widgets/buttons.py", line 423, in drawToolButtonComplexControl
    self.drawToolButtonContent(option, painter, widget)
  File "/usr/lib/python3.10/site-packages/blink/widgets/buttons.py", line 588, in drawToolButtonContent
    pixmap = widget.pixmap(QIcon.Normal)
  File "/usr/lib/python3.10/site-packages/blink/widgets/buttons.py", line 634, in pixmap
    painter.drawPixmap(offset_x, offset_y, pixmap)
TypeError: arguments did not match any overloaded call:
  drawPixmap(self, QRectF, QPixmap, QRectF): argument 1 has unexpected type 'float'
  drawPixmap(self, QRect, QPixmap, QRect): argument 1 has unexpected type 'float'
  drawPixmap(self, Union[QPointF, QPoint], QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, QPoint, QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, QRect, QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, int, int, QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, int, int, int, int, QPixmap): argument 1 has unexpected type 'float'
  drawPixmap(self, int, int, int, int, QPixmap, int, int, int, int): argument 1 has unexpected type 'float'
  drawPixmap(self, int, int, QPixmap, int, int, int, int): argument 1 has unexpected type 'float'
  drawPixmap(self, Union[QPointF, QPoint], QPixmap, QRectF): argument 1 has unexpected type 'float'
  drawPixmap(self, QPoint, QPixmap, QRect): argument 1 has unexpected type 'float'
```

**Comment by tijmenNL** [comment]
Ok, thanks for the info. I will merge when I find some time. 

Our primary repository is using Darcs and this is a mirror, so I can't automatically merge the pull request. Instead I will commit the patch in Darcs and preserve you as the author. Afterwards I will close the pull request. Is that OK by you?

**Comment by jose-lopes** [comment]
It is OK for me. Thanks

**Comment by tijmenNL** [comment]
Merged in https://github.com/AGProjects/blink-qt/commit/33c7f377d173d27b4611d061ca36077805250e78

**Pull request closed without merging**
